# Generated by Django 6.0.2 on 2026-08-10 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_clear_legacy_assistant_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('role', models.CharField(choices=[('chat', 'Chat 模型'), ('agent', 'Agent 模型')], max_length=16, verbose_name='配置角色')),
                ('model_type', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('gemini', 'Google Gemini'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('other', '其他 OpenAI 兼容模型')], default='other', max_length=20, verbose_name='模型提供商')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='API Key')),
                ('base_url', models.URLField(max_length=500, verbose_name='API Base URL')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('max_tokens', models.PositiveIntegerField(default=4096, verbose_name='最大 Token 数')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('top_p', models.FloatField(default=0.9, verbose_name='Top P 参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_model_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'AI Agent 模型配置',
                'verbose_name_plural': 'AI Agent 模型配置',
                'db_table': 'assistant_agent_model_configs',
                'ordering': ['role', '-updated_at'],
            },
        ),
    ]
