# Generated by Django 6.0.2 on 2026-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_add_agent_model_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodelconfig',
            name='model_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('azure_openai', 'Azure OpenAI'), ('anthropic', 'Anthropic Claude'), ('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('gemini', 'Google Gemini'), ('moonshot', 'Moonshot / Kimi'), ('baichuan', '百川智能'), ('minimax', 'MiniMax'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('openrouter', 'OpenRouter'), ('together', 'Together AI'), ('groq', 'Groq'), ('ollama', 'Ollama'), ('vllm', 'vLLM'), ('other', '其他 OpenAI 兼容模型')], default='other', max_length=20, verbose_name='模型提供商'),
        ),
    ]
