# Generated by Django 6.0.2 on 2026-08-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_expand_agent_model_providers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DifyConfig',
        ),
        migrations.RemoveField(
            model_name='assistantsession',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_id',
        ),
    ]
