# Generated by Django 6.0.2 on 2026-08-09 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0013_aiexecutionexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arguments_hash', models.CharField(max_length=64)),
                ('risk_metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已批准'), ('rejected', '已拒绝'), ('expired', '已过期'), ('invalidated', '已失效')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_approval_requests',
            },
        ),
        migrations.CreateModel(
            name='AlphaDispatchIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', '待派发'), ('claimed', '已领取'), ('dispatched', '已派发'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_dispatch_intents',
            },
        ),
        migrations.CreateModel(
            name='AlphaExternalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '超时')], db_index=True, default='pending', max_length=16)),
                ('cancellation_supported', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_external_runs',
            },
        ),
        migrations.CreateModel(
            name='AlphaParameterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=100)),
                ('field_schema', models.JSONField(default=dict)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '待填写'), ('valid', '有效'), ('invalid', '无效')], default='pending', max_length=16)),
                ('validation_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_parameter_requests',
            },
        ),
        migrations.CreateModel(
            name='AlphaPlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveSmallIntegerField(verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('frozen', '已冻结'), ('superseded', '已替代')], db_index=True, default='draft', max_length=16)),
                ('planner_input', models.JSONField(blank=True, default=dict, verbose_name='规划输入快照')),
                ('planner_output', models.JSONField(blank=True, default=dict, verbose_name='规划输出快照')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='内容哈希')),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_plan_revisions',
                'ordering': ['run_id', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='AlphaRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('planner_model', models.CharField(blank=True, default='', max_length=100)),
                ('reflection_model', models.CharField(blank=True, default='', max_length=100)),
                ('planner_input', models.JSONField(blank=True, default=dict)),
                ('planner_output', models.JSONField(blank=True, default=dict)),
                ('reflection_input', models.JSONField(blank=True, default=dict)),
                ('reflection_verdict', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_rounds',
            },
        ),
        migrations.CreateModel(
            name='AlphaRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_request', models.TextField(verbose_name='原始目标')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('collecting_input', '收集参数'), ('planning', '规划中'), ('awaiting_confirmation', '等待确认'), ('executing', '执行中'), ('reflecting', '反思中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='draft', max_length=32)),
                ('round_count', models.PositiveSmallIntegerField(default=0, verbose_name='已完成规划轮次')),
                ('state_version', models.PositiveIntegerField(default=1, verbose_name='状态版本')),
                ('final_output', models.JSONField(blank=True, null=True, verbose_name='最终输出')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlphaTaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_task_dependencies',
            },
        ),
        migrations.CreateModel(
            name='AlphaTaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(max_length=100, verbose_name='任务键')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('skill_name', models.CharField(max_length=120, verbose_name='注册技能名称')),
                ('skill_version', models.CharField(blank=True, default='', max_length=40)),
                ('tier', models.CharField(choices=[('read', '只读'), ('run', '运行'), ('write', '写入')], max_length=16)),
                ('risk_metadata', models.JSONField(blank=True, default=dict)),
                ('normalized_arguments', models.JSONField(blank=True, default=dict)),
                ('arguments_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('awaiting_confirmation', '等待确认'), ('dispatched', '已派发'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('blocked', '阻塞'), ('skipped', '跳过'), ('cancelled', '已取消'), ('superseded', '已替代')], db_index=True, default='pending', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_testing_alpha_task_nodes',
                'ordering': ['revision_id', 'display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='alphaapprovalrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alphaparameterrequest',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_requests', to='ai_testing.alphaplanrevision'),
        ),
        migrations.AddField(
            model_name='alphaapprovalrequest',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='ai_testing.alphaplanrevision'),
        ),
        migrations.AddField(
            model_name='alpharound',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_artifact', to='ai_testing.alphaplanrevision'),
        ),
        migrations.AddField(
            model_name='alpharun',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai_testing.alphaplanrevision', verbose_name='当前计划版本'),
        ),
        migrations.AddField(
            model_name='alpharun',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_runs', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='alpharun',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alpha_runs', to='ai_testing.aiproject', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='alpharound',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ai_testing.alpharun'),
        ),
        migrations.AddField(
            model_name='alphaplanrevision',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ai_testing.alpharun'),
        ),
        migrations.AddField(
            model_name='alphaapprovalrequest',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='ai_testing.alpharun'),
        ),
        migrations.AddField(
            model_name='alphatasknode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphatasknode',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to='ai_testing.alphaplanrevision'),
        ),
        migrations.AddField(
            model_name='alphataskdependency',
            name='depends_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphataskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphaparameterrequest',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameter_requests', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphaexternalrun',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_runs', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphadispatchintent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_intents', to='ai_testing.alphatasknode'),
        ),
        migrations.AddField(
            model_name='alphaapprovalrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='ai_testing.alphatasknode'),
        ),
        migrations.AddIndex(
            model_name='alpharun',
            index=models.Index(fields=['initiated_by', 'status'], name='ai_testing__initiat_2892ce_idx'),
        ),
        migrations.AddIndex(
            model_name='alpharun',
            index=models.Index(fields=['project', 'status'], name='ai_testing__project_393774_idx'),
        ),
        migrations.AddConstraint(
            model_name='alpharound',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='alpha_unique_run_round'),
        ),
        migrations.AddConstraint(
            model_name='alphaplanrevision',
            constraint=models.UniqueConstraint(fields=('run', 'revision_number'), name='alpha_unique_run_revision'),
        ),
        migrations.AddIndex(
            model_name='alphatasknode',
            index=models.Index(fields=['revision', 'status'], name='ai_testing__revisio_f33bfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='alphatasknode',
            constraint=models.UniqueConstraint(fields=('revision', 'task_key'), name='alpha_unique_revision_task_key'),
        ),
        migrations.AddConstraint(
            model_name='alphataskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='alpha_unique_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='alphaparameterrequest',
            constraint=models.UniqueConstraint(fields=('revision', 'task', 'field_key'), name='alpha_unique_parameter_field'),
        ),
        migrations.AddConstraint(
            model_name='alphaexternalrun',
            constraint=models.UniqueConstraint(fields=('task', 'external_reference'), name='alpha_unique_external_reference'),
        ),
        migrations.AddIndex(
            model_name='alphadispatchintent',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ai_testing__status_052992_idx'),
        ),
        migrations.AddIndex(
            model_name='alphaapprovalrequest',
            index=models.Index(fields=['task', 'status', 'expires_at'], name='ai_testing__task_id_7a4a60_idx'),
        ),
    ]
