# Generated by Django 6.0.2 on 2026-08-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0014_alpha_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpharun',
            name='planner_task_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='规划任务ID'),
        ),
    ]
