# Generated by Django 6.0.2 on 2026-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0015_add_alpha_planner_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpharun',
            name='reflection_task_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='反思任务ID'),
        ),
    ]
