# Generated by Django 6.0.2 on 2026-08-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0022_aicase_environment_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionexperience',
            name='last_verified_attempt',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最近验证步骤尝试'),
        ),
        migrations.AddField(
            model_name='aiexecutionexperience',
            name='last_verified_evidence_hashes',
            field=models.JSONField(blank=True, default=list, verbose_name='最近验证证据哈希'),
        ),
        migrations.AddField(
            model_name='aiexecutionexperience',
            name='last_verified_plan_revision',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最近验证计划版本'),
        ),
    ]
