# Generated by Django 6.0.2 on 2026-08-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0024_aiexecutionrecord_environment_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicase',
            name='environment_configuration',
        ),
    ]
