# Generated by Django 6.0.2 on 2026-09-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0027_update_planner_vision_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='dispatch_backend',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='派发后端'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='dispatch_task_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='队列任务ID'),
        ),
        migrations.AddField(
            model_name='aiexecutionrecord',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间'),
        ),
    ]
