# Generated by Django 6.0.2 on 2026-09-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_testing', '0030_action_cache_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVerifiedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_hash', models.CharField(db_index=True, max_length=64, verbose_name='目标哈希')),
                ('source_goal', models.TextField(verbose_name='用例目标')),
                ('ai_case_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='用例 id')),
                ('case_name', models.CharField(blank=True, default='', max_length=255, verbose_name='用例名')),
                ('environment_configuration_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='运行环境 id')),
                ('context_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='规划上下文指纹')),
                ('plan', models.JSONField(default=dict, verbose_name='计划内容')),
                ('plan_hash', models.CharField(max_length=64, verbose_name='计划哈希')),
                ('verified_count', models.PositiveIntegerField(default=0, verbose_name='验证通过次数')),
                ('last_passed_record_id', models.IntegerField(blank=True, null=True, verbose_name='最近通过的执行记录 id')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='最近验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI已验证执行计划',
                'verbose_name_plural': 'AI已验证执行计划',
                'db_table': 'ai_testing_verified_plans',
                'ordering': ['-verified_count', '-last_verified_at'],
                'indexes': [models.Index(fields=['goal_hash', 'environment_configuration_id'], name='ai_verified_plan_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('goal_hash', 'environment_configuration_id', 'context_fingerprint', 'plan_hash'), name='ai_verified_plan_unique')],
            },
        ),
    ]
