# Generated by Django 6.0.2 on 2026-08-29 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_notificationtemplate_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('environment', models.CharField(default='custom', max_length=50, verbose_name='运行环境')),
                ('base_url', models.URLField(blank=True, verbose_name='HTTP基础地址')),
                ('web_url', models.URLField(blank=True, verbose_name='Web地址')),
                ('websocket_url', models.URLField(blank=True, verbose_name='WebSocket地址')),
                ('variables', models.JSONField(default=dict, verbose_name='环境变量')),
                ('auth_profiles', models.JSONField(default=dict, verbose_name='认证角色配置')),
                ('payment_config', models.JSONField(default=dict, verbose_name='支付服务配置')),
                ('model_profiles', models.JSONField(default=dict, verbose_name='模型服务配置')),
                ('runtime_settings', models.JSONField(default=dict, verbose_name='测试运行设置')),
                ('event_device_keys_encrypted', models.TextField(blank=True, default='', verbose_name='事件设备私钥密文')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='请求超时秒数')),
                ('max_workers', models.PositiveIntegerField(default=1, verbose_name='并发数')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '全局环境配置',
                'verbose_name_plural': '全局环境配置',
                'db_table': 'environment_configurations',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
