# Generated by Django 6.0.2 on 2026-07-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0009_add_configuration_environment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiautomationcase',
            new_name='api_automat_suite_i_fc6a97_idx',
            old_name='api_automa_suite_i_b419a1_idx',
        ),
        migrations.RenameIndex(
            model_name='apiautomationcase',
            new_name='api_automat_source__700356_idx',
            old_name='api_automa_source__458c36_idx',
        ),
        migrations.RenameIndex(
            model_name='apiautomationcase',
            new_name='api_automat_executi_9f96da_idx',
            old_name='api_automa_execut_07b919_idx',
        ),
    ]
