# Generated by Django 6.0.2 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0010_normalize_index_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiautomationrun',
            name='current_case_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='当前执行用例'),
        ),
    ]