# Generated by Django 6.0.2 on 2026-07-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0011_add_current_case_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutomationNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('schedule_name', models.CharField(max_length=200)),
                ('execution_status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], max_length=20)),
                ('channel', models.CharField(choices=[('EMAIL', '邮件'), ('WEBHOOK', 'Webhook'), ('MULTI', '邮件与Webhook'), ('NONE', '未配置渠道')], max_length=20)),
                ('status', models.CharField(choices=[('DISPATCHED', '已派发'), ('SKIPPED', '未派发')], max_length=20)),
                ('targets', models.JSONField(blank=True, default=list)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='api_automation.apiautomationproject')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='api_automation.apiautomationrun')),
            ],
            options={
                'db_table': 'api_automation_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apiautomationnotificationlog',
            index=models.Index(fields=['project', 'created_at'], name='api_automat_project_356e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='apiautomationnotificationlog',
            index=models.Index(fields=['run'], name='api_automat_run_id_92f033_idx'),
        ),
    ]