# Generated by Django 6.0.2 on 2026-07-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0012_add_notification_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apiautomationnotificationlog',
            new_name='api_automat_project_46db7e_idx',
            old_name='api_automat_project_356e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='apiautomationnotificationlog',
            new_name='api_automat_run_id_9ac403_idx',
            old_name='api_automat_run_id_92f033_idx',
        ),
    ]
