# Generated by Django 6.0.2 on 2026-07-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0013_rename_api_automat_project_356e2a_idx_api_automat_project_46db7e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAutomationSchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64)),
                ('schema_count', models.PositiveIntegerField(default=0)),
                ('schema_fingerprints', models.JSONField(default=dict)),
                ('change_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_snapshots', to='api_automation.apiautomationproject')),
            ],
            options={
                'db_table': 'api_automation_schema_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='api_automat_project_0f2517_idx')],
            },
        ),
    ]
