# Generated by Django 6.0.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0015_schema_warning_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiautomationconfiguration',
            name='event_device_keys_encrypted',
            field=models.TextField(blank=True, default='', verbose_name='事件设备私钥密文'),
        ),
    ]