# Generated by Django 6.0.2 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0016_configuration_event_device_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiautomationconfiguration',
            name='web_url',
            field=models.URLField(blank=True, verbose_name='Web地址'),
        ),
    ]