# Generated by Django 6.0.2 on 2026-08-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0019_migrate_global_environment_configurations'),
        ('core', '0011_migrate_global_environment_configurations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiautomationrun',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.environmentconfiguration', verbose_name='执行配置'),
        ),
    ]
