# Generated by Django 6.0.2 on 2026-07-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_factory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafactoryrecord',
            name='tool_category',
            field=models.CharField(choices=[('test_data', '数据生成'), ('business', '业务工具'), ('json', 'JSON工具'), ('string', '字符工具'), ('encoding', '编码工具'), ('random', '随机工具'), ('encryption', '加密工具'), ('crontab', 'Crontab工具')], max_length=20, verbose_name='工具分类'),
        ),
        migrations.AlterField(
            model_name='datafactoryrecord',
            name='tool_scenario',
            field=models.CharField(choices=[('test_data', '数据生成'), ('business', '业务工具'), ('json', 'JSON工具'), ('string', '字符工具'), ('encoding', '编码工具'), ('random', '随机工具'), ('encryption', '加密工具'), ('crontab', 'Crontab工具')], max_length=20, verbose_name='使用场景'),
        ),
    ]
