# Generated by Django 6.0.2 on 2026-08-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0009_remove_browser_use_model_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('planner_text', 'AI智能测试 - Planner文本模型'), ('planner_vision', 'AI智能测试 - Planner视觉模型'), ('executor_text', 'AI智能测试 - Executor文本模型'), ('executor_vision', 'AI智能测试 - Executor视觉模型'), ('hermes_agent', 'Hermes Agent'), ('alpha_planner', 'Alpha Planner'), ('alpha_reflection', 'Alpha Reflection')], max_length=20, verbose_name='角色'),
        ),
    ]
